name: Setup Ruby
description: 'Install ruby, and optionally the project dependencies'
inputs:
  version:
    description: 'The version of ruby to setup and run'
    required: true
  install-dependencies:
    description: 'Whether to install the project dependencies'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.version }}

    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: bundle install
