name: Setup Ruby
description: 'Install ruby, and optionally the project dependencies'
inputs:
  version:
    description: 'The version of ruby to setup and run'
    required: true
  install-dependencies:
    description: 'Whether to install the project dependencies'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # v1.318.0
      with:
        ruby-version: ${{ inputs.version }}
        bundler: 2

    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: bundle install
