name: Setup Ruby
description: 'Install ruby, and optionally the project dependencies'
inputs:
  version:
    description: 'The version of ruby to setup and run'
    required: true
  install-dependencies:
    description: 'Whether to install the project dependencies'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
      with:
        ruby-version: ${{ inputs.version }}
        bundler: 2

    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: bundle install
