
module LaunchDarkly
  module Impl
    module Model
      # Called after we have deserialized a flag from JSON (because we received it from LaunchDarkly, or
      # read it from a persistent data store). Generates immutable instances of every parameterized
      # evaluation reason that could be generated by this flag, so we can avoid creating new reason
      # instances during evaluations.
      def preprocess_flag_after_deserializing(flag)
        prereqs = flag[:prerequisites]
        if !prereqs.nil?
          prereqs.each do |prereq|
            prereq[:_reason] = EvaluationReason::prerequisite_failed(prereq[:key])
          end
        end
        rules = flag[:rules]
        if !rules.nil?
          rules.each_index do |i|
            rule = rules[i]
            rule[:_reason] = EvaluationReason::rule_match(i, rule[:id])
          end
        end
      end
    end
  end
end
