source 'https://rubygems.org'

gem 'launchdarkly-server-sdk', path: '..'

gem 'http', '~> 5.1'
gem 'json'
gem "puma", "~> 6.6"
gem "rackup", "~> 2.2"
gem 'sinatra', '>= 4.1'

gem 'rubocop', '~> 1.37', group: 'development'
gem 'rubocop-performance', '~> 1.15', group: 'development'

gem "connection_pool", "~> 2.4"
gem "redis", "~> 5.3"

gem "diplomat", "~> 2.6"

gem "aws-sdk-dynamodb", "~> 1.127"
