name: Publish Documentation
description: 'Publish the documentation to GitHub Pages'
inputs:
  token:
    description: 'Token to use for publishing.'
    required: true

runs:
  using: composite
  steps:
    - uses: launchdarkly/gh-actions/actions/publish-pages@publish-pages-v1.0.2
      name: 'Publish to Github pages'
      with:
        docs_path: docs/build/html/
        github_token: ${{inputs.token}} # For the shared action the token should be a GITHUB_TOKEN<
