name: Quality control checks
description: 'Runs tests, linters, and contract tests'
inputs:
  flaky:
    description: 'Is the platform under test considered flaky?'
    required: false
    default: 'false'
  token:
    description: 'GH token used to fetch the SDK test harness'
    required: true

runs:
  using: composite
  steps:
    - name: Skip flaky tests for jruby
      if: ${{ inputs.flaky == 'true' }}
      shell: bash
      run: echo "SPEC_TAGS=-t '~flaky'" >> $GITHUB_ENV

    - name: Run tests
      shell: bash
      run: bundle exec rspec spec $SPEC_TAGS

    - name: Run RuboCop
      shell: bash
      run: bundle exec rubocop --parallel

    - name: Build contract tests
      if: ${{ inputs.flaky != 'true' }}
      shell: bash
      run: make build-contract-tests

    - name: Start contract test service
      if: ${{ inputs.flaky != 'true' }}
      shell: bash
      run: make start-contract-test-service-bg

    - name: Run contract tests v2
      if: ${{ inputs.flaky != 'true' }}
      uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1
      with:
        test_service_port: 9000
        enable_persistence_tests: true
        token: ${{ inputs.token }}
        stop_service: 'false'

    - name: Run contract tests v3
      if: ${{ inputs.flaky != 'true' }}
      uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1
      with:
        test_service_port: 9000
        enable_persistence_tests: true
        token: ${{ inputs.token }}
        version: v3.0.0-alpha.2