name: Publish Package
description: 'Publish the package to rubygems'
inputs:
  dry_run:
    description: 'Is this a dry run. If so no package will be published.'
    required: true
outputs:
  gem-hash:
    description: "base64-encoded sha256 hashes of distribution files"
    value: ${{ steps.gem-hash.outputs.gem-hash }}

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: 'gems-*'

    - name: Hash gem for provenance
      id: gem-hash
      shell: bash
      run: |
        echo "gem-hash=$(sha256sum launchdarkly-server-sdk-*.gem | base64 -w0)" >> "$GITHUB_OUTPUT"

    - name: Publish Library
      shell: bash
      if: ${{ inputs.dry_run == 'false' }}
      run: gem push launchdarkly-server-sdk-*.gem
