name: Publish Package
description: 'Publish the package to rubygems'
inputs:
  dry_run:
    description: 'Is this a dry run. If so no package will be published.'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: 'gems-*'
        merge-multiple: true

    - name: Publish Library
      shell: bash
      if: ${{ inputs.dry_run == 'false' }}
      run: ls launchdarkly-server-sdk-*.gem | xargs -I {} gem push {}
