name: Run CI
on:
  push:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      LD_SKIP_DATABASE_TESTS: 0

    strategy:
      matrix:
        ruby-version:
          - '3.0'
          - '3.1'
          - '3.2'
          - jruby-9.4

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
      consul:
        image: hashicorp/consul
        ports:
          - 8500:8500

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # If you only need the current version keep this.

      - uses: ./.github/actions/ci
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: ./.github/actions/build-docs
        if: ${{ !startsWith(matrix.ruby-version, 'jruby') }}

  build-windows:
    runs-on: windows-latest

    env:
      LD_SKIP_DATABASE_TESTS: 1

    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler: 2.2.33

      - name: Install dependencies
        run: bundle _2.2.33_ install

      - name: Run tests
        run: bundle _2.2.33_ exec rspec spec
