name: Run CI
on:
  push:
    branches: [main, "feat/**"]
    paths-ignore:
      - "**.md" # Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, "feat/**"]
    paths-ignore:
      - "**.md"

jobs:
  build-linux:
    uses: ./.github/workflows/build-gem.yml
    strategy:
      matrix:
        version: ["3.2", "3.4", "jruby-9.4"]
    with:
      version: ${{ matrix.version }}

  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          version: "3.2"

      - uses: ./.github/actions/build-docs

  build-windows:
    runs-on: windows-latest

    env:
      LD_SKIP_DATABASE_TESTS: 1

    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          version: "3.2"

      - name: Run tests
        run: bundle exec rspec spec
