name: Run CI
on:
  push:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main, 'feat/**' ]
    paths-ignore:
      - '**.md'

jobs:
  build-linux-oldest:
    uses: ./.github/workflows/build-gem.yml
    with:
      version: '3.0'

  build-linux-latest:
    uses: ./.github/workflows/build-gem.yml
    with:
      version: '3.2'

  build-linux-jruby:
    uses: ./.github/workflows/build-gem.yml
    with:
      version: 'jruby-9.4'

  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          version: '3.0'

      - uses: ./.github/actions/build-docs

  build-windows:
    runs-on: windows-latest

    env:
      LD_SKIP_DATABASE_TESTS: 1

    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          version: '3.0'

      - name: Run tests
        run: bundle _2.2.33_ exec rspec spec
