on:
  workflow_dispatch:

name: Publish Documentation
jobs:
  build-publish-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Needed in this case to write github pages.

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup
        with:
          version: "3.2"
          install-dependencies: false

      - uses: ./.github/actions/build-docs

      - uses: ./.github/actions/publish-docs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
