name: Publish Package
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Is this a dry run. If so no package will be published."
        type: boolean
        required: true

jobs:
  build-ruby-gem:
    uses: ./.github/workflows/build-gem.yml
    with:
      version: "3.2"

  build-jruby-gem:
    uses: ./.github/workflows/build-gem.yml
    with:
      version: "jruby-9.4"

  publish:
    runs-on: ubuntu-latest
    needs: ["build-ruby-gem", "build-jruby-gem"]

    permissions:
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write
      attestations: write # Needed for actions/attest.

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          version: "3.2"
          install-dependencies: false

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.2.0
        name: "Get rubygems API key"
        if: ${{ format('{0}', inputs.dry_run) == 'false' }}
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: "/production/common/releasing/rubygems/api_key = GEM_HOST_API_KEY"

      - uses: ./.github/actions/build-docs

      - uses: ./.github/actions/publish
        id: publish
        with:
          dry_run: ${{ inputs.dry_run }}

      - uses: ./.github/actions/publish-docs
        if: ${{ format('{0}', inputs.dry_run) == 'false' }}
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Attest build provenance
        if: ${{ format('{0}', inputs.dry_run) == 'false' }}
        uses: actions/attest@v4
        with:
          subject-path: 'launchdarkly-server-sdk-*.gem'
